services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_recipe_bot_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - recipe_default

  postgres:
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - recipe_bot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5432 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - recipe_default

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_recipe_bot_data:/var/lib/grafana
    ports:
      - "3050:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - recipe_default
    depends_on:
      - prometheus

networks:
  recipe_default:

volumes:
  prometheus_recipe_bot_data:
  grafana_recipe_bot_data:
  recipe_bot_postgres_data:
